### ISSUE TITLE
Check if working

### ISSUE THREAD

**Issue by Lux-Delux** [alleyinteractive/wp-redis#4]
Hello, just found this project as I wanted to implement redis object cache for wordpress so first thanks for the effort!

Secondly, is there any way to check if things are working properly?

**Comment by danielbachhuber** [comment]
Hi @ddem1,

Essentially, to check if things are working, you'll want to confirm that data persists in your object cache. With a tool like WP-CLI, you can do something like this to confirm it's not working:

```
salty-wordpress ➜  wordpress-trunk.dev  wp cache set apple banana
Success: Set object 'apple' in group ''.
salty-wordpress ➜  wordpress-trunk.dev  wp cache get apple
Error: Object with key 'apple' and group '' not found.
```

When it is working, the value would be found in the cache.

**Comment by joshkoenig** [comment]
Also, we'll be adding some documentation for this soon. Thanks for taking
an interest!
